### ISSUE TITLE
Inconcistend use of horizontal rule <hr>

### ISSUE THREAD

**Issue by bedroesb** [AustralianBioCommons/how-to-guides#13]
![image](https://user-images.githubusercontent.com/44875756/179056606-e2e73bb5-ab12-413b-8f5f-5f8f39d45191.png)

I saw that there are multiple pages with horizontal rules in between the content by manually adding them in the markdown `---`.

It would be nicer I think if this is done trough CSS on the H2 if compartmentalizing between sections is wanted

**Comment by supernord** [comment]
@bedroesb - good idea - this would be a custom addition to the theme?

**Comment by bedroesb** [comment]
I would add it as a class here: https://github.com/AustralianBioCommons/how-to-guides/blob/main/_sass/_custom_classes.scss

**Comment by bedroesb** [comment]
I can make a PR if you want :)

**Comment by supernord** [comment]
Yes please 😃
